# Generated by Django 4.2.20 on 2025-03-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_white', models.CharField(max_length=100)),
                ('player_black', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('checkmate', 'Checkmate'), ('stalemate', 'Stalemate'), ('draw', 'Draw')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_number', models.IntegerField()),
                ('move_notation', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='chess.chessgame')),
            ],
        ),
    ]
